// <auto-generated />
using System;
using Emm.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emm.Infrastructure.Migrations
{
    [DbContext(typeof(XDbContext))]
    [Migration("20250823080914_Naruto")]
    partial class Naruto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.Asset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssetAdditionId")
                        .HasColumnType("bigint");

                    b.Property<long>("AssetModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssetAdditionId");

                    b.HasIndex("AssetModelId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisplayName");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganizationUnitId");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetCategories_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AssetCategories_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetCategories_Name");

                    b.ToTable("AssetCategories", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssetCategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<long?>("AssetTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("ParentId")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId")
                        .HasDatabaseName("IX_AssetModels_AssetCategoryId");

                    b.HasIndex("AssetTypeId")
                        .HasDatabaseName("IX_AssetModels_AssetTypeId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetModels_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AssetModels_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_AssetModels_Name");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_AssetModels_ParentId");

                    b.ToTable("AssetModels", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModelParameter", b =>
                {
                    b.Property<long>("AssetModelId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParameterId")
                        .HasColumnType("bigint");

                    b.HasKey("AssetModelId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("AssetModelParameters", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetParameter", b =>
                {
                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParameterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AssetId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("AssetParameters", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetCategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId")
                        .HasDatabaseName("IX_AssetTypes_AssetCategoryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetTypes_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AssetTypes_IsActive");

                    b.HasIndex("Name", "AssetCategoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetTypes_Name_AssetCategoryId");

                    b.ToTable("AssetTypes", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetTypeParameter", b =>
                {
                    b.Property<long>("AssetTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParameterId")
                        .HasColumnType("bigint");

                    b.HasKey("AssetTypeId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("AssetTypeParameters", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetModelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ParameterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParameterId");

                    b.HasIndex("AssetModelId", "IsActive")
                        .HasDatabaseName("IX_MaintenancePlanDefinitions_AssetModelId_IsActive");

                    b.ToTable("MaintenancePlanDefinitions", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ParameterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ParameterId");

                    b.ToTable("MaintenancePlanInstances", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanJobStepDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("MaintenancePlanDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationUnitId");

                    b.HasIndex("MaintenancePlanDefinitionId", "Order")
                        .HasDatabaseName("IX_MaintenancePlanJobStepDefinitions_MaintenancePlanDefinitionId_Order");

                    b.ToTable("MaintenancePlanJobStepDefinitions", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanJobStepInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MaintenancePlanInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MaintenancePlanInstanceId");

                    b.HasIndex("OrganizationUnitId");

                    b.ToTable("MaintenancePlanJobStepInstances", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetTransaction.AssetAddition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DecisionDate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DecisionNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetAdditions_Code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AssetAdditions_CreatedAt");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("IX_AssetAdditions_LocationId");

                    b.HasIndex("OrganizationUnitId")
                        .HasDatabaseName("IX_AssetAdditions_OrganizationUnitId");

                    b.ToTable("AssetAdditions", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetTransaction.AssetAdditionLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetAdditionId")
                        .HasColumnType("bigint");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("AssetModelId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetAdditionId")
                        .HasDatabaseName("IX_AssetAdditionLines_AssetAdditionId");

                    b.HasIndex("AssetCode")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetAdditionLines_AssetCode");

                    b.HasIndex("AssetModelId")
                        .HasDatabaseName("IX_AssetAdditionLines_AssetModelId");

                    b.HasIndex("AssetAdditionId", "AssetCode")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetAdditionLines_AssetAdditionId_AssetCode");

                    b.ToTable("AssetAdditionLines", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OperationShiftId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OperationShiftId1")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Level");

                    b.HasIndex("OperationShiftId");

                    b.HasIndex("OperationShiftId1");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.HasIndex("OperationShiftId", "Timestamp");

                    b.HasIndex("Type", "Level");

                    b.ToTable("OperationLogs", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("PrimaryEmpolyeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ScheduledEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LocationId");

                    b.HasIndex("ScheduledStartTime");

                    b.HasIndex("Status");

                    b.ToTable("OperationShifts", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OperationShiftId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OperationShiftId1")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode");

                    b.HasIndex("AssetId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OperationShiftId");

                    b.HasIndex("OperationShiftId1");

                    b.HasIndex("Status");

                    b.HasIndex("OperationShiftId", "AssetId")
                        .IsUnique();

                    b.ToTable("OperationShiftAssets", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OperationShiftId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OperationShiftId1")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OperationShiftId");

                    b.HasIndex("OperationShiftId1");

                    b.HasIndex("Order");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("OperationShiftId", "Order")
                        .IsUnique();

                    b.ToTable("OperationTasks", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftParameterReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OperationTaskId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OperationTaskId1")
                        .HasColumnType("bigint");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParameterId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReadBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReadingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StringValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OperationTaskId");

                    b.HasIndex("OperationTaskId1");

                    b.HasIndex("ParameterCode");

                    b.HasIndex("ParameterId");

                    b.HasIndex("ReadingTime");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("OperationTaskId", "AssetId");

                    b.HasIndex("AssetId", "ParameterId", "ReadingTime");

                    b.ToTable("ParameterReadings", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTaskCheckpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OperationTaskId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OperationTaskId1")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRequired");

                    b.HasIndex("OperationTaskId");

                    b.HasIndex("OperationTaskId1");

                    b.HasIndex("Status");

                    b.ToTable("TaskCheckpoints", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_Code");

                    b.HasIndex("OrganizationUnitId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Locations_Code");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.OrganizationUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("OrganizationUnitLevelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationUnits_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_OrganizationUnits_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationUnits_Name");

                    b.HasIndex("OrganizationUnitLevelId");

                    b.ToTable("OrganizationUnits", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.OrganizationUnitLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationUnitLevels_Name");

                    b.ToTable("OrganizationUnitLevels", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.ParameterCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ParameterCatalogs", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long?>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Emm.Infrastructure.Data.SequenceNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CurrentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("NumberLength")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Prefix", "TableName", "NumberLength")
                        .IsUnique()
                        .HasDatabaseName("IX_SequenceNumbers_Prefix_NumberLength_SequenceNumber");

                    b.ToTable("SequenceNumbers", (string)null);
                });

            modelBuilder.Entity("Emm.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "CreatedAt");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.Asset", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetTransaction.AssetAddition", null)
                        .WithMany()
                        .HasForeignKey("AssetAdditionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetModel", null)
                        .WithMany()
                        .HasForeignKey("AssetModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Organization.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Organization.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModel", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetCategory", null)
                        .WithMany()
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetType", null)
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetModel", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModelParameter", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetModel", null)
                        .WithMany("EfParameters")
                        .HasForeignKey("AssetModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.ParameterCatalog", null)
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetParameter", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.Asset", null)
                        .WithMany("EfParameters")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.ParameterCatalog", null)
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetType", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetCategory", null)
                        .WithMany()
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetTypeParameter", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetType", null)
                        .WithMany("_parameters")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.ParameterCatalog", null)
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanDefinition", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetModel", null)
                        .WithMany("EfMaintenancePlanDefinitions")
                        .HasForeignKey("AssetModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.ParameterCatalog", null)
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanInstance", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.Asset", null)
                        .WithMany("EfMaintenancePlanInstances")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.ParameterCatalog", null)
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanJobStepDefinition", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.MaintenancePlanDefinition", null)
                        .WithMany("EfJobSteps")
                        .HasForeignKey("MaintenancePlanDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Organization.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanJobStepInstance", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.MaintenancePlanInstance", null)
                        .WithMany("EfJobSteps")
                        .HasForeignKey("MaintenancePlanInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Organization.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetTransaction.AssetAddition", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Organization.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Organization.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetTransaction.AssetAdditionLine", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetTransaction.AssetAddition", null)
                        .WithMany("_assetAdditionLines")
                        .HasForeignKey("AssetAdditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetModel", null)
                        .WithMany()
                        .HasForeignKey("AssetModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftLog", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.OperationShift", null)
                        .WithMany("EfLogs")
                        .HasForeignKey("OperationShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Operations.OperationShift", null)
                        .WithMany("Logs")
                        .HasForeignKey("OperationShiftId1");
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftAsset", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.OperationShift", null)
                        .WithMany("EfAssets")
                        .HasForeignKey("OperationShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Operations.OperationShift", null)
                        .WithMany("Assets")
                        .HasForeignKey("OperationShiftId1");
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTask", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.OperationShift", null)
                        .WithMany("EfTasks")
                        .HasForeignKey("OperationShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Operations.OperationShift", null)
                        .WithMany("Tasks")
                        .HasForeignKey("OperationShiftId1");
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftParameterReading", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.OperationShiftTask", null)
                        .WithMany("EfReadings")
                        .HasForeignKey("OperationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Operations.OperationShiftTask", null)
                        .WithMany("Readings")
                        .HasForeignKey("OperationTaskId1");
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTaskCheckpoint", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.OperationShiftTask", null)
                        .WithMany("EfCheckpoints")
                        .HasForeignKey("OperationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Operations.OperationShiftTask", null)
                        .WithMany("Checkpoints")
                        .HasForeignKey("OperationTaskId1");
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.Employee", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Organization.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.OrganizationUnit", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Organization.OrganizationUnitLevel", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.User", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Organization.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.Asset", b =>
                {
                    b.Navigation("EfMaintenancePlanInstances");

                    b.Navigation("EfParameters");
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModel", b =>
                {
                    b.Navigation("EfMaintenancePlanDefinitions");

                    b.Navigation("EfParameters");
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetType", b =>
                {
                    b.Navigation("_parameters");
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanDefinition", b =>
                {
                    b.Navigation("EfJobSteps");
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanInstance", b =>
                {
                    b.Navigation("EfJobSteps");
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetTransaction.AssetAddition", b =>
                {
                    b.Navigation("_assetAdditionLines");
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShift", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("EfAssets");

                    b.Navigation("EfLogs");

                    b.Navigation("EfTasks");

                    b.Navigation("Logs");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTask", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("EfCheckpoints");

                    b.Navigation("EfReadings");

                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
