// <auto-generated />
using System;
using Emm.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emm.Infrastructure.Migrations
{
    [DbContext(typeof(XDbContext))]
    [Migration("20251125033509_XShuka")]
    partial class XShuka
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.Asset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssetAdditionId")
                        .HasColumnType("bigint");

                    b.Property<long>("AssetModelId")
                        .HasColumnType("bigint");

                    b.Property<long>("AssetTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssetAdditionId");

                    b.HasIndex("AssetModelId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisplayName");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganizationUnitId");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetCategories_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AssetCategories_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetCategories_Name");

                    b.ToTable("AssetCategories", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssetCategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<long?>("AssetTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("ParentId")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ThumbnailFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId")
                        .HasDatabaseName("IX_AssetModels_AssetCategoryId");

                    b.HasIndex("AssetTypeId")
                        .HasDatabaseName("IX_AssetModels_AssetTypeId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetModels_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AssetModels_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_AssetModels_Name");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_AssetModels_ParentId");

                    b.ToTable("AssetModels", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModelImage", b =>
                {
                    b.Property<long>("AssetModelId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetModelId", "FileId");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("AssetModelImages", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModelParameter", b =>
                {
                    b.Property<long>("AssetModelId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParameterId")
                        .HasColumnType("bigint");

                    b.HasKey("AssetModelId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("AssetModelParameters", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetParameter", b =>
                {
                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParameterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AssetId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("AssetParameters", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetCategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId")
                        .HasDatabaseName("IX_AssetTypes_AssetCategoryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetTypes_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AssetTypes_IsActive");

                    b.HasIndex("Name", "AssetCategoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetTypes_Name_AssetCategoryId");

                    b.ToTable("AssetTypes", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetTypeParameter", b =>
                {
                    b.Property<long>("AssetTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParameterId")
                        .HasColumnType("bigint");

                    b.HasKey("AssetTypeId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("AssetTypeParameters", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetModelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PlanType")
                        .HasColumnType("int");

                    b.Property<string>("RRule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssetModelId", "IsActive", "PlanType")
                        .HasDatabaseName("IX_MaintenancePlanDefinitions_AssetModelId_IsActive_PlanType");

                    b.ToTable("MaintenancePlanDefinitions", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanJobStepDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MaintenancePlanDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationUnitId");

                    b.HasIndex("MaintenancePlanDefinitionId", "Order")
                        .HasDatabaseName("IX_MaintenancePlanJobStepDefinitions_MaintenancePlanDefinitionId_Order");

                    b.ToTable("MaintenancePlanJobStepDefinitions", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.ParameterBasedMaintenanceTrigger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("MaintenancePlanDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("ParameterId")
                        .HasColumnType("bigint");

                    b.Property<int>("TriggerCondition")
                        .HasColumnType("int");

                    b.Property<decimal>("TriggerValue")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("MaintenancePlanDefinitionId")
                        .IsUnique();

                    b.HasIndex("ParameterId");

                    b.HasIndex("TriggerCondition");

                    b.HasIndex("ParameterId", "IsActive");

                    b.HasIndex("MaintenancePlanDefinitionId", "ParameterId", "IsActive");

                    b.ToTable("ParameterBasedMaintenanceTriggers", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetTransaction.AssetAddition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DecisionDate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DecisionNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetAdditions_Code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AssetAdditions_CreatedAt");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("IX_AssetAdditions_LocationId");

                    b.HasIndex("OrganizationUnitId")
                        .HasDatabaseName("IX_AssetAdditions_OrganizationUnitId");

                    b.ToTable("AssetAdditions", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetTransaction.AssetAdditionLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetAdditionId")
                        .HasColumnType("bigint");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("AssetModelId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetAdditionId")
                        .HasDatabaseName("IX_AssetAdditionLines_AssetAdditionId");

                    b.HasIndex("AssetCode")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetAdditionLines_AssetCode");

                    b.HasIndex("AssetModelId")
                        .HasDatabaseName("IX_AssetAdditionLines_AssetModelId");

                    b.HasIndex("AssetAdditionId", "AssetCode")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetAdditionLines_AssetAdditionId_AssetCode");

                    b.ToTable("AssetAdditionLines", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.CheckpointTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CheckpointTemplates_Code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CheckpointTemplates_CreatedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CheckpointTemplates_IsActive");

                    b.HasIndex("Version")
                        .HasDatabaseName("IX_CheckpointTemplates_Version");

                    b.ToTable("CheckpointTemplates", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.CheckpointTemplateAssetCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetCategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("CheckpointTemplateId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId")
                        .HasDatabaseName("IX_CheckpointTemplateAssetCategories_CategoryId");

                    b.HasIndex("AssignedAt")
                        .HasDatabaseName("IX_CheckpointTemplateAssetCategories_AssignedAt");

                    b.HasIndex("CheckpointTemplateId")
                        .HasDatabaseName("IX_CheckpointTemplateAssetCategories_TemplateId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CheckpointTemplateAssetCategories_IsActive");

                    b.HasIndex("CheckpointTemplateId", "AssetCategoryId")
                        .HasDatabaseName("IX_CheckpointTemplateAssetCategories_TemplateId_CategoryId");

                    b.ToTable("CheckpointTemplateAssetCategories", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.CheckpointTemplateField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CheckpointTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long?>("MasterDataTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointTemplateId")
                        .HasDatabaseName("IX_CheckpointTemplateFields_TemplateId");

                    b.HasIndex("FieldType")
                        .HasDatabaseName("IX_CheckpointTemplateFields_FieldType");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CheckpointTemplateFields_IsActive");

                    b.HasIndex("MasterDataTypeId")
                        .HasDatabaseName("IX_CheckpointTemplateFields_MasterDataTypeId");

                    b.HasIndex("Order")
                        .HasDatabaseName("IX_CheckpointTemplateFields_Order");

                    b.HasIndex("CheckpointTemplateId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CheckpointTemplateFields_TemplateId_Code");

                    b.ToTable("CheckpointTemplateFields", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("PrimaryEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ScheduledEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganizationUnitId");

                    b.HasIndex("PrimaryEmployeeId");

                    b.HasIndex("ScheduledStartTime");

                    b.HasIndex("Status");

                    b.ToTable("OperationShifts", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OperationShiftId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode");

                    b.HasIndex("AssetId");

                    b.HasIndex("OperationShiftId");

                    b.HasIndex("Status");

                    b.HasIndex("OperationShiftId", "AssetId")
                        .IsUnique();

                    b.ToTable("OperationShiftAssets", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OperationShiftId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Level");

                    b.HasIndex("OperationShiftId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.HasIndex("OperationShiftId", "Timestamp");

                    b.HasIndex("Type", "Level");

                    b.ToTable("OperationShiftLogs", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftParameterReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OperationTaskId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParameterId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ReadingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StringValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("TaskCheckpointId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TaskCheckpointLinkedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("OperationTaskId");

                    b.HasIndex("ParameterCode");

                    b.HasIndex("ParameterId");

                    b.HasIndex("ReadingTime");

                    b.HasIndex("OperationTaskId", "AssetId");

                    b.HasIndex("AssetId", "ParameterId", "ReadingTime");

                    b.ToTable("OperationShiftParameterReadings", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OperationShiftId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OperationShiftId");

                    b.HasIndex("Order");

                    b.HasIndex("OperationShiftId", "Order")
                        .IsUnique();

                    b.ToTable("OperationShiftTasks", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTaskCheckpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CheckpointTemplateId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsWithAttachedMaterial")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LinkedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("OperationTaskId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointTemplateId");

                    b.HasIndex("OperationTaskId");

                    b.ToTable("OperationShiftTaskCheckpoints", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTaskCheckpointValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CheckpointId")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TemplateFieldId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId")
                        .HasDatabaseName("IX_CheckpointValues_CheckpointId");

                    b.HasIndex("DisplayText")
                        .HasDatabaseName("IX_CheckpointValues_DisplayText");

                    b.HasIndex("TemplateFieldId")
                        .HasDatabaseName("IX_CheckpointValues_TemplateFieldId");

                    b.HasIndex("Value")
                        .HasDatabaseName("IX_CheckpointValues_Value");

                    b.HasIndex("CheckpointId", "TemplateFieldId")
                        .IsUnique()
                        .HasDatabaseName("IX_CheckpointValues_CheckpointId_TemplateFieldId");

                    b.ToTable("OperationShiftTaskCheckpointValues", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTaskStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("OperationTaskId")
                        .HasColumnType("bigint");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("IsResolved");

                    b.HasIndex("OperationTaskId");

                    b.HasIndex("StartTime");

                    b.HasIndex("OperationTaskId", "EventType");

                    b.HasIndex("OperationTaskId", "IsResolved");

                    b.ToTable("OperationShiftTaskStatusHistory", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_Code");

                    b.HasIndex("OrganizationUnitId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Locations_Code");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.OrganizationUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("OrganizationUnitLevelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationUnits_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_OrganizationUnits_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationUnits_Name");

                    b.HasIndex("OrganizationUnitLevelId");

                    b.ToTable("OrganizationUnits", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.OrganizationUnitLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationUnitLevels_Name");

                    b.ToTable("OrganizationUnitLevels", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.ParameterCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UnitOfMeasureId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("ParameterCatalogs", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BaseUnitId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("ConversionFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Symbol");

                    b.HasIndex("UnitType");

                    b.HasIndex("IsActive", "UnitType");

                    b.ToTable("UnitOfMeasures", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Subfolder")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Subfolder");

                    b.HasIndex("UploadedAt");

                    b.ToTable("UploadedFiles", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long?>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccessTokenJti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenJti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenJti")
                        .HasDatabaseName("IX_UserSessions_AccessTokenJti");

                    b.HasIndex("RefreshTokenJti")
                        .HasDatabaseName("IX_UserSessions_RefreshTokenJti");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("IX_UserSessions_UserId_RevokedAt");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("Emm.Infrastructure.Data.SequenceNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("CurrentNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("NumberLength")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Prefix", "TableName", "NumberLength")
                        .IsUnique()
                        .HasDatabaseName("UX_SequenceNumbers_Prefix_Table_NumberLength");

                    b.ToTable("SequenceNumbers", (string)null);
                });

            modelBuilder.Entity("Emm.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "CreatedAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.Asset", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetTransaction.AssetAddition", null)
                        .WithMany()
                        .HasForeignKey("AssetAdditionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetModel", null)
                        .WithMany()
                        .HasForeignKey("AssetModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Organization.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Organization.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModel", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetCategory", null)
                        .WithMany()
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetType", null)
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetModel", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModelImage", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetModel", null)
                        .WithMany("Images")
                        .HasForeignKey("AssetModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModelParameter", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetModel", null)
                        .WithMany("Parameters")
                        .HasForeignKey("AssetModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.ParameterCatalog", null)
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetParameter", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.Asset", null)
                        .WithMany("Parameters")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.ParameterCatalog", null)
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetType", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetCategory", null)
                        .WithMany()
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetTypeParameter", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetType", null)
                        .WithMany("_parameters")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.ParameterCatalog", null)
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanDefinition", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetModel", null)
                        .WithMany("MaintenancePlanDefinitions")
                        .HasForeignKey("AssetModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanJobStepDefinition", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.MaintenancePlanDefinition", null)
                        .WithMany("JobSteps")
                        .HasForeignKey("MaintenancePlanDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Organization.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.ParameterBasedMaintenanceTrigger", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetCatalog.MaintenancePlanDefinition", null)
                        .WithOne("ParameterBasedTrigger")
                        .HasForeignKey("Emm.Domain.Entities.AssetCatalog.ParameterBasedMaintenanceTrigger", "MaintenancePlanDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetTransaction.AssetAddition", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Organization.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.Organization.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetTransaction.AssetAdditionLine", b =>
                {
                    b.HasOne("Emm.Domain.Entities.AssetTransaction.AssetAddition", null)
                        .WithMany("_assetAdditionLines")
                        .HasForeignKey("AssetAdditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emm.Domain.Entities.AssetCatalog.AssetModel", null)
                        .WithMany()
                        .HasForeignKey("AssetModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.CheckpointTemplateAssetCategory", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.CheckpointTemplate", null)
                        .WithMany("AssetCategories")
                        .HasForeignKey("CheckpointTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.CheckpointTemplateField", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.CheckpointTemplate", null)
                        .WithMany("Fields")
                        .HasForeignKey("CheckpointTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftAsset", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.OperationShift", null)
                        .WithMany("Assets")
                        .HasForeignKey("OperationShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftLog", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.OperationShift", null)
                        .WithMany("Logs")
                        .HasForeignKey("OperationShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftParameterReading", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.OperationShiftTask", null)
                        .WithMany("Readings")
                        .HasForeignKey("OperationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTaskCheckpoint", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.CheckpointTemplate", null)
                        .WithMany()
                        .HasForeignKey("CheckpointTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Emm.Domain.Entities.Operations.OperationShiftTask", null)
                        .WithMany("Checkpoints")
                        .HasForeignKey("OperationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTaskCheckpointValue", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.OperationShiftTaskCheckpoint", null)
                        .WithMany("Values")
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTaskStatusHistory", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Operations.OperationShiftTask", null)
                        .WithMany("StatusHistories")
                        .HasForeignKey("OperationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.Employee", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Organization.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Emm.Domain.Entities.Organization.OrganizationUnit", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Organization.OrganizationUnitLevel", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.ParameterCatalog", b =>
                {
                    b.HasOne("Emm.Domain.Entities.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emm.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.HasOne("Emm.Domain.Entities.UnitOfMeasure", "BaseUnit")
                        .WithMany("DerivedUnits")
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");
                });

            modelBuilder.Entity("Emm.Domain.Entities.User", b =>
                {
                    b.HasOne("Emm.Domain.Entities.Organization.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Emm.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("Emm.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.Asset", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetModel", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("MaintenancePlanDefinitions");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.AssetType", b =>
                {
                    b.Navigation("_parameters");
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetCatalog.MaintenancePlanDefinition", b =>
                {
                    b.Navigation("JobSteps");

                    b.Navigation("ParameterBasedTrigger");
                });

            modelBuilder.Entity("Emm.Domain.Entities.AssetTransaction.AssetAddition", b =>
                {
                    b.Navigation("_assetAdditionLines");
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.CheckpointTemplate", b =>
                {
                    b.Navigation("AssetCategories");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShift", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTask", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("Readings");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("Emm.Domain.Entities.Operations.OperationShiftTaskCheckpoint", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Emm.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("DerivedUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
