using Emm.Domain.Abstractions;
using Emm.Domain.Exceptions;
using Emm.Domain.ValueObjects;

namespace Emm.Domain.Entities.AssetCatalog;

public class Asset : AggregateRoot, IAuditableEntity
{
    private const int MaxParametersPerAsset = 100;
    public NaturalKey Code { get; private set; }
    public bool IsCodeGenerated { get; private set; }
    public string DisplayName { get; private set; } = null!;
    public Guid AssetCategoryId { get; private set; }
    public string? AssetCategoryCode { get; private set; }
    public string? AssetCategoryName { get; private set; }
    public Guid AssetModelId { get; private set; }
    public string? AssetModelCode { get; private set; }
    public string? AssetModelName { get; private set; }
    public Guid AssetTypeId { get; private set; }
    public string? AssetTypeCode { get; private set; }
    public string? AssetTypeName { get; private set; }
    public Guid? AssetAdditionId { get; private set; }
    public Guid OrganizationUnitId { get; private set; }
    public Guid LocationId { get; private set; }
    public string? Description { get; private set; }
    public bool IsLooked { get; private set; }
    public AssetStatus Status { get; private set; }

    public AuditMetadata Audit { get; private set; } = null!;
    public void SetAudit(AuditMetadata audit) => Audit = audit;

    private readonly List<AssetParameter> _parameters;
    public IReadOnlyCollection<AssetParameter> Parameters => _parameters;

    private Asset()
    {
        _parameters = [];
    }

    public Asset(
        bool isCodeGenerated,
        NaturalKey code,
        string displayName,
        Guid assetModelId,
        Guid? assetCategoryId,
        Guid? assetTypeId,
        Guid organizationUnitId,
        Guid locationId,
        Guid? assetAdditionId,
        string? description = null)
    {
        // Id already generated by AggregateRoot base class

        ValidateDisplayName(displayName);
        DomainGuard.AgainstInvalidForeignKey(assetModelId, nameof(AssetModelId));
        DomainGuard.AgainstInvalidForeignKey(organizationUnitId, nameof(OrganizationUnitId));
        DomainGuard.AgainstInvalidForeignKey(locationId, nameof(LocationId));
        DomainGuard.AgainstInvalidForeignKey(assetCategoryId, nameof(AssetCategoryId));
        DomainGuard.AgainstInvalidForeignKey(assetTypeId, nameof(AssetTypeId));

        _parameters = [];

        IsCodeGenerated = isCodeGenerated;
        Code = code;
        DisplayName = displayName;
        Description = description;
        AssetModelId = assetModelId;
        AssetCategoryId = assetCategoryId ?? Guid.Empty;
        AssetTypeId = assetTypeId ?? Guid.Empty;
        OrganizationUnitId = organizationUnitId;
        LocationId = locationId;
        AssetAdditionId = assetAdditionId;

        // RaiseDomainEvent(new AssetCreatedEvent(Id, code, displayName));
    }

    public void MakeSnapshot(
        string assetModeCode,
        string assetModelName,
        string assetTypeCode,
        string assetTypeName,
        string assetCategoryCode,
        string assetCategoryName)
    {
        AssetModelCode = assetModeCode;
        AssetModelName = assetModelName;
        AssetTypeCode = assetTypeCode;
        AssetTypeName = assetTypeName;
        AssetCategoryCode = assetCategoryCode;
        AssetCategoryName = assetCategoryName;
    }

    public void Update(
        string displayName,
        string? description,
        Guid organizationUnitId,
        Guid locationId)
    {
        ValidateDisplayName(displayName);
        DomainGuard.AgainstInvalidForeignKey(organizationUnitId, nameof(OrganizationUnitId));
        DomainGuard.AgainstInvalidForeignKey(locationId, nameof(LocationId));

        DisplayName = displayName;
        Description = description;
        OrganizationUnitId = organizationUnitId;
        LocationId = locationId;

        // RaiseDomainEvent(new AssetUpdatedEvent(Id, DisplayName));
    }

    public void AddParameter(Guid parameterId, bool isMaintenanceParameter = false, decimal value = 0, decimal valueToMaintenance = 0, string? parameterCode = null, string? parameterName = null, string? unit = null)
    {
        DomainGuard.AgainstInvalidForeignKey(parameterId, nameof(parameterId));

        if (_parameters.Count >= MaxParametersPerAsset)
            throw new DomainException($"Cannot exceed {MaxParametersPerAsset} parameters per asset");

        if (_parameters.Any(p => p.ParameterId == parameterId))
            throw new DomainException($"Parameter {parameterId} already exists in this asset");

        var parameter = new AssetParameter(
            parameterId,
            isMaintenanceParameter,
            value,
            valueToMaintenance,
            parameterCode,
            parameterName,
            unit);
        _parameters.Add(parameter);

        // RaiseDomainEvent(new AssetParameterAddedEvent(Id, parameterId));
    }

    public void AddParameters(params Guid[] parameterIds)
    {
        if (parameterIds == null || parameterIds.Length == 0)
            return;

        foreach (var parameterId in parameterIds)
        {
            AddParameter(parameterId);
        }
    }

    public void Operate()
    {
        Status = AssetStatus.Operating;
    }

    public void Idle()
    {
        Status = AssetStatus.Idle;
    }

    public void UpdateParameterCurrentValue(Guid parameterId, decimal newValue)
    {
        DomainGuard.AgainstInvalidForeignKey(parameterId, nameof(parameterId));

        var parameter = _parameters.FirstOrDefault(p => p.ParameterId == parameterId);

        if (parameter == null)
            throw new DomainException($"Parameter {parameterId} not found in this asset");

        parameter.UpdateValue(newValue);

        // RaiseDomainEvent(new AssetParameterUpdatedEvent(Id, parameterId, newValue));
    }

    public void RemoveParameter(Guid parameterId)
    {
        DomainGuard.AgainstInvalidForeignKey(parameterId, nameof(parameterId));

        var parameter = _parameters.FirstOrDefault(p => p.ParameterId == parameterId);

        if (parameter == null)
            throw new DomainException($"Parameter {parameterId} not found in this asset");

        _parameters.Remove(parameter);
        // RaiseDomainEvent(new AssetParameterRemovedEvent(Id, parameterId));
    }

    private static void ValidateDisplayName(string displayName)
    {
        if (string.IsNullOrWhiteSpace(displayName))
            throw new DomainException("Display name cannot be empty");

        if (displayName.Length > 200)
            throw new DomainException("Display name cannot exceed 200 characters");
    }
}

public enum AssetStatus
{
    Maintenance = 1,     // Đang bảo trì
    Incident = 2,        // Đang gặp sự cố
    Operating = 3,       // Đang vận hành
    Idle = 4             // Đang rảnh
}
